### ISSUE TITLE
Sitemap for posts doesn't work

### ISSUE THREAD

**Issue by daviesgeek** [anomalylabs/posts-module#18]
The sitemap for posts (default `/posts/sitemap.xml`) doesn't work because the [TypeController](https://github.com/anomalylabs/posts-module/blob/master/src/PostsModuleServiceProvider.php#L113) route takes precedence over the sitemap

**Comment by RyanThompson** [comment]
<img width="1440" alt="screen shot 2016-03-18 at 1 21 03 am" src="https://cloud.githubusercontent.com/assets/1099967/13869946/f1164f82-eca7-11e5-8c3a-014cf99cb281.png">

**Comment by RyanThompson** [comment]
What's your root/ resources config for addons look like?

**Comment by daviesgeek** [comment]
I was missing `core/anomaly/sitemap-extension` in the `eager` array :flushed:
