### ISSUE TITLE
Error when date isn't explicitly set

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/posts-module#2]
![screen shot 2015-05-20 at 07 48 21](https://cloud.githubusercontent.com/assets/6826637/7720393/a1cb9436-fec4-11e4-9a68-6576cb438954.png)

**Comment by j-hubb** [comment]
This is still a problem since only the placeholder is set with then current date on a new post and not the value.

**Comment by RyanThompson** [comment]
Be sure to composer update - let me know if this exists after.

**Comment by j-hubb** [comment]
It's still a problem http://d.pr/i/1dMIP

**Comment by RyanThompson** [comment]
Ahhh I get what you are saying.. Total brain fart.

**Comment by RyanThompson** [comment]
Fixed - pull core, posts and the datetime field type. Led to a couple other anomalies (business pun!).
