### ISSUE TITLE
Create/Edit Post Error

### ISSUE THREAD

**Issue by sebgc** [anomalylabs/posts-module#20]
Please see the errors below. 
1. Image one occurs when creating a new post.
2. Image two show the stack trace that occurs when updating a new post. The update is saved but the stack fails with response as shown.
   ![create-post-error](https://cloud.githubusercontent.com/assets/683506/16265853/f1f8e4fc-3881-11e6-901d-cab7a1c21ab1.jpg)
   ![screencapture-dev-mobisuperpyro-local-admin-posts-edit-9-1466596790713](https://cloud.githubusercontent.com/assets/683506/16265802/a82e3624-3881-11e6-94da-ed75a48d87df.png)

**Comment by huglester** [comment]
@RyanThompson this can probably be closed, since it's old issue and posts are working correctly?
