### ISSUE TITLE
Bugs in edit assigned fields.

### ISSUE THREAD

**Issue by oimken** [anomalylabs/posts-module#33]
When edit the assigned field in `posts type`
A Exception will throwout:
```The $field parameter is required when creating an assignment.```

I check the route and `AssignmentsController` I think I maybe fixed that bug:

in `Anomaly\PostsModule\Http\Controller\Admin\AssignmentsController`  

```public function edit(AssignmentFormBuilder $builder, StreamRepositoryInterface $streams)
   {
       return $builder
           ->setStream($streams->find($this->route->getParameter('stream')))
           ->render($this->route->getParameter('id'));
   }
```
change 
`->render($this->route->getParameter('id'));`  
to 
`->render($this->route->getParameter('assignment'));`

bug fixed.

**Comment by RyanThompson** [comment]
Good catch! Patched: https://github.com/anomalylabs/posts-module/commit/625d634915990cc89b772d2b33a803c1273c7957
